### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ravindra1992** [jllarraz/AndroidPassportReader#1]
@jllarraz  ,I have tried to test but by clicking on the automatic section then camera open but scanning is not done. Always shows the OCR Failed bar.

**Comment by jllarraz** [comment]
Hi,

You must put your phone horizontal and then be sure that the passport MRZ
page it's centered and focus on the screen. The main thing that should be
focused it's the second line of the MRZ.

Also I updated the ocr engine on Friday getting rid of tesseract and using
instead Ml kit, try to update the project.

Note: try to scan a European passport as are the ones that I have used for
testing.

Best regards,
Jose Luis Larraz

**Comment by jllarraz** [comment]
I have uploaded a video where I show how the app works.
https://youtu.be/kuIkZ1ZktCk
