### ISSUE TITLE
OCR Problem

### ISSUE THREAD

**Issue by tolgasaglam** [jllarraz/AndroidPassportReader#11]
i am waiting a lot for scanning but ocr failed writing on left side. i printed sample photo but its not working again.

**Comment by sertunc** [comment]
any update? @tolgasaglam

**Comment by jllarraz** [comment]
Could you provide a sample of the MRZ that you are trying to read?

**Comment by sertunc** [comment]
@jllarraz my mrz data I<TURA05B592941<31219575508<<<8907264M2708241TUR<<<<<<<<<<<2SELEN<<CAHIT<SERTUNC<<<<<<<<<<

**Comment by sertunc** [comment]
@jllarraz nfc working with Turkey Id Card. Thanks a lot

**Comment by jllarraz** [comment]
Hi,

This is a TD1 id card, the project is about passports. As I dont have any TD1 card to test I will close the issue. Anyway if you want to try you just have to replace the REGEX expressions to detect the TD1 cards in the class "OcrMrzDetectorProcessor.kt". As an example this regex will validate the first line of a TD1 id card

`(?<documentType>[IAC]{1})(?<discretionType>[A-Z<]{1})(?<issuingCountry>[A-Z<]{3})(?<documentNumber>[A-Z0-9<]{9})(?<checkDigit>[0-9<]{1})(?<optional>[A-Z0-9<]{15})`

Feel free to try
