### ISSUE TITLE
ID Card

### ISSUE THREAD

**Issue by sertunc** [jllarraz/AndroidPassportReader#12]
Hello i am from Turkey and I can not use ocr for Turkey Id Card. How can I fix it? Thank you

**Comment by jllarraz** [comment]
You must change the Regex expressions and check how to read TD1 cards with NFC. I am sure that it´s quite similar to Passports. You can change the regex expressions in the class "OcrMrzDetectorProcessor.kt" and you can read about the TD1 cards in [Wikipedia](https://en.wikipedia.org/wiki/Machine-readable_passport#Official_travel_documents) as an Starting point
