### ISSUE TITLE
Question: About screenOrientation

### ISSUE THREAD

**Issue by sertunc** [jllarraz/AndroidPassportReader#13]
Hello @jllarraz how can I use screenOrientation in portrait mode on mrz fragment. Thank you

**Comment by jllarraz** [comment]
Could you please stop adding issues that are not project related. If you need in your app to have another screen orientation or whatever just modify the source code provided but just copying it without understanding whats going on is a really bad practice. 

Anyway just go to the manifest and change the screen orientation

`<activity android:name=".ui.activities.CameraActivity"
            android:screenOrientation="landscape"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar.FullScreen"
            android:windowSoftInputMode="stateAlwaysHidden" >`

**Comment by sertunc** [comment]
I don't copy the code without understanding.... I don't know this platform (android) and I've been working with kotlin for a weeks. I'm in a hurry and I have to train this job.. Anyway thanks for everything and I am sorry for the adding issues...
