### ISSUE TITLE
Active Authentication with country certificate file

### ISSUE THREAD

**Issue by sertunc** [jllarraz/AndroidPassportReader#17]
Hello, How can I use my country signing certificate file (.cer or .pem) with that method ? Thank you

https://github.com/jllarraz/AndroidPassportReader/blob/master/app/src/main/java/example/jllarraz/com/passportreader/utils/PassportNFC.kt#L612

**Comment by jllarraz** [comment]
Active Authetnication is still not implemented and I don't know when it will be. Anjyway you can take a look to [Icao](https://www.icao.int/Security/FAL/PKD/BVRT/Pages/Access.aspx  ) and review the documentation about active authentication. Most of the methods are already implemented but not tested. I advice you to start looking to the documentation of the electronic documents.

**Comment by sertunc** [comment]
Thank you @jllarraz

**Comment by jllarraz** [comment]
I have added Country Verifying Certification Authority to the example, you just need to download your country master list
https://jmrtd.org/certificates.shtml

**Comment by sertunc** [comment]
huge thanks @jllarraz ...

**Comment by jllarraz** [comment]
I made a little mistake in the post, it's not "Country Verifying Certification Authority" it's "Country Signing Certification Authority", I still don't know where to get the CVCA

**Comment by sertunc** [comment]
Hello @jllarraz again thank you that commit. But my country has no master list. I have just "CSCATR.pem" and "CSCA_TR.crt" files so I want to just copy these file (pem or crt) to my phone and use them. But I can not find which line I have to modify? Thank you

**Comment by jllarraz** [comment]
This is where you must add the certificates before reading the passport [Keystore](https://github.com/jllarraz/AndroidPassportReader/blob/445a57b8a5d35c619cc04aa159b8233321185e52/app/src/main/java/example/jllarraz/com/passportreader/ui/fragments/NfcFragment.kt#L87)

How you create that keystore or the content it's up to you. I am using it just to store the certificates of the master list. SO you just initialize MRTDTrustStore with whatever set of cetificates you have

**Comment by akeilox** [comment]
Hi @sertunc can you share the .pem and .crt files that you are testing with, perhaps via google drive or similar

**Comment by sertunc** [comment]
hello @jllarraz I used the the master list in which my country is also but still did not active authentication

**Comment by jllarraz** [comment]
Hi,

For EAC you will need a  CVCA certificate and normally only the police have access to those certificates (As far as I know), as they give you access to the biometry embedded into the passport (Fingerprint, Iris).

If you have that certificate you can add it to the MRTDTrustStore at the same point of the CSCA certificates from the master list

Best regards

**Comment by sertunc** [comment]
No I just have to do an active authentication to see if this passport has been copied or not

**Comment by sertunc** [comment]
I get the following error both in this version and in the previous version "net.sf.scuba.smartcards.CardServiceException: Internal Authenticate failed"

https://github.com/jllarraz/AndroidPassportReader/blob/master/app/src/main/java/example/jllarraz/com/passportreader/utils/PassportNFC.kt#L654

**Comment by jllarraz** [comment]
Can you provide more information like the real crash? I just can't tell you too much with the information provided. It will be also helpful to know which are the parameters passed

**Comment by sertunc** [comment]
You are absolutely right, but I'm so tired that it came out of my mind.

val aaResult = (service as PassportService).doAA(dg15File!!.publicKey, sodFile!!.digestAlgorithm, sodFile!!.signerInfoDigestAlgorithm, challenge)

in this line my parameters
publicKey->8d9f71fcca....
digestAlgorithm->SHA-256
signatureAlgorithm->SHA-256
challenge-> any byte array 8 lenght

error screenshot
[https://imgur.com/xG0972j](url)

**Comment by jllarraz** [comment]
Can you try to replace the 
private val BC_PROVIDER = JMRTDSecurityProvider.bouncyCastleProvider
by
private val BC_PROVIDER = JMRTDSecurityProvider.spongyCastleProvider
in PassportNfc.kt (it's in the companion object)

**Comment by sertunc** [comment]
I made the change you wanted, but nothing changed. I also add the detailed log. The "tag was lost" error caught my attention, do you think it might have something to do with it?

`04-29 13:11:20.634 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: Inspecting card access file
04-29 13:11:20.644 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: DEBUG: failed to get card access file: File not found, CAPDU = 00A4020C02011C, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)
04-29 13:11:20.644 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:255)
04-29 13:11:20.674 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: Attempt to read EF.COM before BAC failed with: No valid file selected, path = null
04-29 13:11:22.144 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.getDG14File(PassportNFC.kt:1420)
04-29 13:11:22.144 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:341)
04-29 13:11:22.204 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.getCVCAFile(PassportNFC.kt:1450)
04-29 13:11:22.204 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:347)
04-29 13:11:22.214 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: Found DGs: [1, 2, 5, 11, 12, 15]
04-29 13:11:22.214 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: Using hash algorithm SHA-256
04-29 13:11:22.234 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG1 during HT verification because file could not be read.
04-29 13:11:28.594 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.getDG3File(PassportNFC.kt:1345)
04-29 13:11:28.594 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:455)
04-29 13:11:35.044 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.getDG7File(PassportNFC.kt:1375)
04-29 13:11:35.044 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:467)
04-29 13:11:36.164 4673-5110/example.jllarraz.com.passportreader I/PassportNFC: digestEncryptionAlgorithm = SHA256withRSA
04-29 13:11:36.184 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG1 during HT verification because file could not be read.
04-29 13:11:36.184 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG2 during HT verification because file could not be read.
04-29 13:11:36.184 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG5 during HT verification because file could not be read.
04-29 13:11:36.194 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG11 during HT verification because file could not be read.
04-29 13:11:36.194 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG12 during HT verification because file could not be read.
04-29 13:11:36.194 4673-5110/example.jllarraz.com.passportreader W/PassportNFC: Skipping DG15 during HT verification because file could not be read.
04-29 13:11:36.634 4673-5110/example.jllarraz.com.passportreader I/org.jmrtd.protocol: Exception during transmission of command APDU = 00880000082B1B22123764BFCC00
    net.sf.scuba.smartcards.CardServiceException: Tag was lost.
        at net.sf.scuba.smartcards.IsoDepCardService.transmit(IsoDepCardService.java:123)
        at org.jmrtd.protocol.SecureMessagingAPDUSender.transmit(SecureMessagingAPDUSender.java:88)
        at org.jmrtd.protocol.AAAPDUSender.sendInternalAuthenticate(AAAPDUSender.java:83)
        at org.jmrtd.protocol.AAProtocol.doAA(AAProtocol.java:74)
        at org.jmrtd.PassportService.doAA(PassportService.java:508)
        at example.jllarraz.com.passportreader.utils.PassportNFC.verifyAA(PassportNFC.kt:654)
        at example.jllarraz.com.passportreader.utils.PassportNFC.verifySecurity(PassportNFC.kt:541)
        at example.jllarraz.com.passportreader.utils.NFCDocumentTag$handleTag$1.call(NFCDocumentTag.kt:39)
        at example.jllarraz.com.passportreader.utils.NFCDocumentTag$handleTag$1.call(NFCDocumentTag.kt:23)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
04-29 13:11:36.644 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.verifyAA(PassportNFC.kt:654)
04-29 13:11:36.644 4673-5110/example.jllarraz.com.passportreader W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.verifySecurity(PassportNFC.kt:541)
`

**Comment by jllarraz** [comment]
If the tag is lost you can't read it

**Comment by sertunc** [comment]
You are right but I am not doing anything to lose connection and I never take the card from the phone. Do you think I should increase the ncf timeout ?

**Comment by jllarraz** [comment]
It seems like a good option

**Comment by sertunc** [comment]
Exactly, I increased the ncf timeout and error changed and falls on the last part of catch block

https://www.codepile.net/pile/D36VxV3O

**Comment by jllarraz** [comment]
Hi,

Unfortunately I don't have any document right now with dg15, so I can't test the AA. But I am trying to get one, not sure that I will manage but it's all that I can do.

**Comment by jllarraz** [comment]
I finally got a document with a Dg15 file in it. Initially I was getting the same error than you but after debugging I found that the problem was that the passport was disconnecting. I have increased the timeout to 5 seconds and everything works fine

**Comment by sertunc** [comment]
I still have failed. I'm in search of different dg15's to try. thanks a lot

**Comment by sertunc** [comment]
Hello @jllarraz, I updated masterlist from [here ](https://www.icao.int/Security/FAL/PKD/BVRT/Pages/Access.aspx). But please can you explain [that line in your code](https://github.com/jllarraz/AndroidPassportReader/blob/master/app/src/main/java/example/jllarraz/com/passportreader/utils/PassportNFC.kt#L838) because all the time pkixChain size 1 and docSigningCertificate = 1 so I for loop continue and line 846 I fail

**Comment by MrLongg71** [comment]
hi guys, any solution about this error? some card field "activeAuthentication": false (func verifyAA())
@sertunc 

thank SO much!

**Comment by ALAALDIN2016** [comment]
hello, can any one help me to create and verify Active Authontication AA
