### ISSUE TITLE
OCR Read Failure

### ISSUE THREAD

**Issue by RuudAzlan** [jllarraz/AndroidPassportReader#20]
Hello, I cloned your project and tried to scan my passport but it show ocr read failure. Any advise how to fix this issue. 
![Screenshot_20200827_170355_example jllarraz com passportreader](https://user-images.githubusercontent.com/70058926/91420869-cdd8fc00-e887-11ea-87d1-6d485be6f20f.jpg)

**Comment by jllarraz** [comment]
Check that your passport is compliant with the REGEX expressions during the OCR 
https://github.com/jllarraz/AndroidPassportReader/blob/057475f2ead622b7a577b50fdabd5df6e8c2f65f/app/src/main/java/example/jllarraz/com/passportreader/mlkit/OcrMrzDetectorProcessor.kt#L89

**Comment by RuudAzlan** [comment]
My apologies the ocr read failed appear on the camera once i click Automatic button in the apps not while scanning the passport.
Thank you.
