### ISSUE TITLE
CSCA Certificate

### ISSUE THREAD

**Issue by isha2188** [jllarraz/AndroidPassportReader#21]
Hi,
The project is too good, could you please tell in somewhat detail what changes i have to made for another country.As all the things are working fine but i got the failed csca in authentication section when i scanned the passport of another country.Actually i do not have master list api for that country but i have .pem file for that country.Could you please help me to come out in this situation.

Thank You!

**Comment by naveenkrnl** [comment]
No, I can't help you

**Comment by jllarraz** [comment]
You need to look for something like this
[StackOverflow](https://stackoverflow.com/questions/24137463/how-to-load-public-certificate-from-pem-file/24139603)
