### ISSUE TITLE
OCR issue with one of the passports

### ISSUE THREAD

**Issue by akeilox** [jllarraz/AndroidPassportReader#22]
The OCR is working fine with most of passports I have tried. 
However there is one odd case where the OCR is not working or taking too long (i tried many times and managed to detect at like 30th try).
I am not sure if its the middle name presence or a regular expression issue.

MRZ looks like the following;
PADFGPOL<<MGAN<IEW<<<<<<<<<<<<<<<<<<<<<<<<<
E8652878K0DFG7109211F2904271S7930812E<<<<<64

**Comment by jllarraz** [comment]
Your issue was related to the check digit for the document number, in your case is 0 but most of the time was read as O. I have improved the regex expressions to improve this. You should sync the project again and try to read your passport

**Comment by akeilox** [comment]
@jllarraz are you referring to the 10th position on 2nd line?
Wikipedia page of MRZ shows that as numeric 1-9  ( https://en.wikipedia.org/wiki/Machine-readable_passport )

pos.   length   chars
10       | 1     | numeric | Check digit over digits 1–9
20       | 1     | numeric | Check digit over digits 14–19
28      | 1      | numeric | Check digit over digits 22–27
43      | 1      | numeric+< | Check digit over digits 29–42 (may be < if all characters are <)
44      | 1      | numeric | Check digit over digits 1–10, 14–20, and 22–43

**Comment by jllarraz** [comment]
Exactly, one thing is what ML_KIT reads (in this case O) and another what it should be (a 0). Anyway just update the project and try again
