### ISSUE TITLE
 File google-services.json is missing. 

### ISSUE THREAD

**Issue by nabaanahith** [jllarraz/AndroidPassportReader#24]
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\google-services.json
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\src\nullnull\google-services.json
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\src\debug\google-services.json
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\src\nullnullDebug\google-services.json
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\src\nullnull\debug\google-services.json
  C:\Users\Nabaa Nahith\Downloads\AndroidPassportReader-master\AndroidPassportReader-master\app\src\debug\nullnull\google-services.json

**Comment by jllarraz** [comment]
You need to deploy your own google-services.json file. You can get it from
your firebase console.

**Comment by nabaanahith** [comment]
ok thanks
