### ISSUE TITLE
Active Auth Failed Due To this exception

### ISSUE THREAD

**Issue by zekiamani** [jllarraz/AndroidPassportReader#34]
Im getting this error in PasportrNFC class.  How can get active auth?

DEBUG: this exception wasn't caught in verification logic (< 0.4.8) -- MO 3. Type is

After that AA is always failing.kj

**Comment by MrLongg71** [comment]
hi guys, any solution about this error? some card field "activeAuthentication": false (func verifyAA())
@zekiamani 

thank SO much!

**Comment by jllarraz** [comment]
I didnt find any solution that issue
