### ISSUE TITLE
Active Auth Failed due to exception

### ISSUE THREAD

**Issue by zekierciyas** [jllarraz/AndroidPassportReader#35]
DEBUG: this exception wasn't caught in verification logic (< 0.4.8) -- MO 3. Type is

How can i make active auth?

**Comment by OscarBerggren** [comment]
Have you managed to fix this? I always get the exception "signer initialised with wrong digest for trailer 13516"

**Comment by jllarraz** [comment]
I haven't fixed it yet.

**Comment by OscarBerggren** [comment]
I´m just a little confused by what this comment means:
"check that digestAlgorithm = "SHA1" in this case, check (and re-initialize) rsaAASignature (and rsaAACipher)."

What would we be "checking" in this case?

And even if I reinitialize the values like this

         if (digestAlgorithm == "SHA1") {
                    rsaAASignature = Signature.getInstance("SHA1WithRSA/ISO9796-2", BC_PROVIDER)
                    rsaAACipher = Cipher.getInstance("RSA/NONE/NoPadding")

                    rsaAASignature = Signature.getInstance(signatureAlgorithm, BC_PROVIDER)
                    rsaAACipher.init(Cipher.DECRYPT_MODE, rsaPublicKey)
                    rsaAASignature!!.initVerify(rsaPublicKey)
                }
                
                It´s wrong. Am I on the right track?

**Comment by jllarraz** [comment]
As far as I know the new passports from 2016 or 2018 have a different way
of doing it. I didn't have the chance to review the new documentation. But
I think that you can get it on Icao website

Otherwise I think that you are in the right track.

**Comment by evrenay** [comment]
> Have you managed to fix this? I always get the exception "signer initialised with wrong digest for trailer 13516"

is there any new development ?

**Comment by jllarraz** [comment]
Hi,

I am afraid that no. I just don't have the time right now to look into that
issue.

Best regards

**Comment by evrenay** [comment]
Hi, I couldn't solve this error for 1 week. Do you have any suggestions to solve it?

**Comment by MrLongg71** [comment]
hi guys, any solution about this error? some card field "activeAuthentication": false (func `verifyAA()`)
@jllarraz @evrenay @zekierciyas @OscarBerggren 

thank SO much!

**Comment by rbrouwer** [comment]
I will be nice and tell what probably goes wrong.

In the plaintext variable is a 1 or 2 byte trailer (like you can also see in Util.recoverMessage). Based on that trailer the signature is SHA1, SHA224, SHA256, SHA384 or SHA512. (Refer to ICAO 9303 part 11 - 6.1.2.2 RSA)

Most likely the document you scanned did not SHA1 its RSA AA, but used one of the other digests. The trailer tells you which was used.
