### ISSUE TITLE
Could not find io.fotoapparat

### ISSUE THREAD

**Issue by Yuhanun** [jllarraz/AndroidPassportReader#39]
Running into some issues with the fotoapparat dependency in Android Studio.

```java
Could not find io.fotoapparat:fotoapparat:2.7.0.
Required by:
    project :app
Search in build.gradle files
```

Is this a known issue or is this new?

**Comment by jllarraz** [comment]
That's a dependency issue, you should check that you can access the
repositories.

**Comment by Yuhanun** [comment]
How should I check that? I'm not sure how tbh.

I can see the repository in my browser just fine and I can see the dependency be present with version 2.7.0 in JCentral.

Can i check if i have access?

**Comment by jllarraz** [comment]
Android studio have a check connection option somewhere. Anyway you can
also invalidate the imports and force a sync again. Or if everything fails
download that dependency manually and install it manually in your local
maven repository. Take a look at install third party dependencies in maven

**Comment by Yuhanun** [comment]
Re-starting the download process from scratch.

How about the following error:

```
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
```

**Comment by jllarraz** [comment]
You need to deploy your own google-services.json file.

https://developers.google.com/android/guides/google-services-plugin

**Comment by Yuhanun** [comment]
Alright yeah sorry I'm having a ton of issues with just building this, do you have a guide written anywhere on getting this built and deployed?

```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

**Comment by jllarraz** [comment]
You just have to put your JSON file for Google services and click sync.
That's all
