### ISSUE TITLE
Permanent address gets truncated

### ISSUE THREAD

**Issue by akeilox** [jllarraz/AndroidPassportReader#4]
Upon reading the passport, in details view the Permanent address field gets truncated after 12 characters. 

Is there any simple solution to show the full address; i.e. expand the field in the view?

I am not sure if same issue applies to other fields.

**Comment by jllarraz** [comment]
That's just UI, I am sure that you are able to find a good solution for
your problem. You shouldn't be doing a hard copy of the project for your
application
