### ISSUE TITLE
There is no NFC available.

### ISSUE THREAD

**Issue by tahafarooqui** [jllarraz/AndroidPassportReader#5]
Whenever I try automatic scan, It says no NFC available. Secondly, When I open camera on left it says OCR failure. Can you please resolve this issues. Thanks

**Comment by jllarraz** [comment]
The application has been tested in multiple devices and that error that you comment has never appeared. What's your phone model? And be sure that you have NFC enable in your phone. Remember that some phones don't have NFC capabilities

**Comment by tahafarooqui** [comment]
I am using Oppo f3 and it doesn't  have NFC. Is it possible to use this app without NFC ?

**Comment by jllarraz** [comment]
Read biometric passports require NFC enable devices, You can't read passports without NFC.

**Comment by tahafarooqui** [comment]
Is it possible to read MRZ code using ML Kit on simple passports. I don't want to use NFC.

**Comment by zakblacki** [comment]
Yes you can use passport without NFC enable I used some other library with my phone and worked fine blinkid-android unfortunately this one isn't Open Source it require license to use 
Here is another one free [Mrz-Scanner](https://github.com/codebasepk/mrz-scanner) but I'm facing another issue this one as well but it should work fine with you
