### ISSUE TITLE
Not working ID with two sides

### ISSUE THREAD

**Issue by zakblacki** [jllarraz/AndroidPassportReader#9]
This appear to work only for US passport/ID 
My Algerian ID can't be recognised....
Most likely because our Card ID country has two side the picture is on upfront and the mrz is on the back since it doesn't store two sides like (BlinkID)

**Comment by jllarraz** [comment]
Hi,

I have tested it with European passports, I can't tell you about the
argelian one as I don't have any to test. But if they followed the standard
it should work

Best regards

**Comment by zakblacki** [comment]
Most likely because our Card ID country has two side the picture is on upfront and the mrz is on the back

**Comment by zakblacki** [comment]
I'm facing another problem though when downgrade to API 19 and launch Camera on my Huawei it open and close directly  

Logcat 

12-17 09:48:10.690 2280-19811/? E/CameraService: getCameraCharacteristics: Only HAL module version V2 or higher supports static metadata
12-17 09:48:10.690 2280-2794/? E/CameraService: getCameraCharacteristics: Only HAL module version V2 or higher supports static metadata
12-17 09:48:10.760 3251-3251/? E/ConnectSDK: Could not get the reporting service
12-17 09:48:10.820 2280-19811/? E/CameraUtils: open file error /sys/kernel/debug/boardid/common/camera/faceIgnoreCount
12-17 09:48:10.830 2280-19811/? E/CameraCapSnapshot: mPictureFmt = 825382478
12-17 09:48:10.830 2280-19811/? E/CameraCapSnapshot: mPictureFmt = 842094158
12-17 09:48:10.850 3251-3251/? E/xt9input: alpha_data::dlm_swap_language(00, 020C) FAILED, status = 26
12-17 09:48:10.970 2280-2794/? E/FocusManager: enter startGsensorStatCollect()
12-17 09:48:10.970 2280-2794/? E/FocusManager: exit startGsensorStatCollect()
12-17 09:48:10.970 2826-5192/? E/BroadcastQueue: processNextBroadcast log test
12-17 09:48:11.010 2280-13848/? E/IppAlgoAntiBanding: invalid MemBlock!
12-17 09:48:11.010 2280-13852/? E/GsensorStatCollectThread: null pointer,sensor.
12-17 09:48:11.040 2280-13848/? E/IppAlgoAntiBanding: invalid MemBlock!
12-17 09:48:11.260 12095-12441/example.jllarraz.com.passportreader E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: gt: No acceptable module found. Local version is 0 and remote version is 0.
12-17 09:48:11.290 12095-12441/example.jllarraz.com.passportreader E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: gt: No acceptable module found. Local version is 0 and remote version is 0.
12-17 09:48:11.340 2826-2844/? E/BroadcastQueue: processNextBroadcast log test
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 3 is not owned by the client (state=2)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 0 is not owned by the client (state=0)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 1 is not owned by the client (state=0)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 2 is not owned by the client (state=0)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 3 is not owned by the client (state=2)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 4 is not owned by the client (state=0)
12-17 09:48:11.390 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-8] cancelBuffer: slot 6 is not owned by the client (state=3)
12-17 09:48:11.400 2280-2280/? E/FocusManager: enter stopGsensorStatCollect()
12-17 09:48:11.400 2280-2280/? E/FocusManager: exit stopGsensorStatCollect()
12-17 09:48:11.590 2280-3402/? E/CameraService: getCameraCharacteristics: Only HAL module version V2 or higher supports static metadata
12-17 09:48:11.590 2280-2280/? E/CameraService: getCameraCharacteristics: Only HAL module version V2 or higher supports static metadata
12-17 09:48:11.700 3251-3251/? E/ConnectSDK: Could not get the reporting service
12-17 09:48:11.730 2280-3402/? E/CameraUtils: open file error /sys/kernel/debug/boardid/common/camera/faceIgnoreCount
12-17 09:48:11.730 2280-3402/? E/CameraCapSnapshot: mPictureFmt = 825382478
12-17 09:48:11.730 2280-3402/? E/CameraCapSnapshot: mPictureFmt = 842094158
12-17 09:48:11.880 2280-2280/? E/FocusManager: enter startGsensorStatCollect()
12-17 09:48:11.880 2280-2280/? E/FocusManager: exit startGsensorStatCollect()
12-17 09:48:11.910 2280-13903/? E/GsensorStatCollectThread: null pointer,sensor.
12-17 09:48:11.910 2280-13899/? E/IppAlgoAntiBanding: invalid MemBlock!
12-17 09:48:11.950 2280-13899/? E/IppAlgoAntiBanding: invalid MemBlock!
12-17 09:48:12.160 12095-12441/example.jllarraz.com.passportreader E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: gt: No acceptable module found. Local version is 0 and remote version is 0.
12-17 09:48:12.190 12095-12441/example.jllarraz.com.passportreader E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: gt: No acceptable module found. Local version is 0 and remote version is 0.
12-17 09:48:12.270 2826-2844/? E/BroadcastQueue: processNextBroadcast log test
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 3 is not owned by the client (state=2)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 4 is not owned by the client (state=3)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 0 is not owned by the client (state=0)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 1 is not owned by the client (state=0)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 2 is not owned by the client (state=0)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 3 is not owned by the client (state=2)
12-17 09:48:12.300 12095-12446/example.jllarraz.com.passportreader E/BufferQueue: [unnamed-12095-9] cancelBuffer: slot 4 is not owned by the client (state=3)
12-17 09:48:12.310 2280-2794/? E/FocusManager: enter stopGsensorStatCollect()
12-17 09:48:12.310 2280-2794/? E/FocusManager: exit stopGsensorStatCollect()
12-17 09:48:12.460 3251-3251/? E/xt9input: alpha_data::dlm_swap_language(00, 020C) FAILED, status = 26

**Comment by jllarraz** [comment]
Hi,

Just some clarifications
1-The app works with 2 sides passports as I have tested it with Irish card passports.
2-You don't care about the picture of the person in the passport as the only thing that you need is the MRZ to access the chip (I suggest you read about how the electronic passport works to clarify your doubts)
3-You need a phone with NFC support otherwise you can't read the nfc chip integrated in the passport

Best regards
